Mobilebuilder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from index import views as index_views
from authentication import views as authen_views
from django.contrib.auth import views as auth_views
from transaction import views as trans_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('index.urls')), 
    url(r'^authentication/', include('authentication.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^usersetup/', include('usersetup.urls')),
    url(r'^project/',include('project.urls')),
    url(r'^transaction/', include('transaction.urls')),
    url(r'^schema/',include('schema.urls')),
    url(r'^transactionview/',include('transactionview.urls')),
    url(r'^logintemplate/',include('logintemplate.urls')),
    url(r'^hometemplate/',include('hometemplate.urls')),
    url(r'^actions/',include('actions.urls')),
    url(r'^reportview/',include('reportview.urls')),
    url(r'^syncmaster/',include('syncmaster.urls')),
    url(r'^generateprocess/',include('generateprocess.urls')),
    url(r'^login/',authen_views.login,name='login'),
    url(r'^$', index_views.base, name='base'),
    url(r'^signout/', index_views.signout, name='signout'),
    url(r'^transindex/',trans_views.transindex, name='transindex'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^favicon.ico$',RedirectView.as_view(url='/static/maincss/images/user.png')),
    url(r'^rolesetup/',include('rolesetup.urls')),
    url(r'^smssetup/',include('smssetup.urls')),
    url(r'^notification/',include('notification.urls')),
    url(r'^printformat/',include('printformat.urls')),
    url(r'^eventconfiguration/',include('eventconfiguration.urls'))
]

home/urls.py
from django.conf.urls import include, url
from . import views


app_name ='home'
urlpatterns = [
	url(r'^main/', views.main, name='main'),
		]

reportview/urls.py
from django.conf.urls import url
from . import views
#from .views import getSqlComponents


app_name = 'reportview'
urlpatterns = [
    url(r'^repoviewdetails/$', views.reportview, name='repoviewdetails'),
    url(r'^saveReports/$', views.saveReports, name='saveReports'),
    url(r'^editReport/(?P<title>\d+)/$', views.reportedit, name='editReport'),
    url(r'^editmodal/(?P<title>\d+)/$', views.editmodal, name='editmodal'),
    url(r'^updateReport/(?P<reportId>\d+)/$', views.updateReport, name='updateReport'),
    url(r'^delReport/(?P<reportId>\d+)/$', views.delReport, name='delReport'),
    url(r'^parammodal/(?P<title>\d+)/$', views.parammodal, name='parammodal'),
    url(r'^saveparams/(?P<repoid>\d+)/$',views.saveparams,name ='saveparams'),
    url(r'^parameditmodal/(?P<title>\d+)/(?P<pk>\d+)/$', views.parameditmodal, name='parameditmodal'),
    url(r'^fieldmodal/(?P<title>\d+)/$', views.fieldmodal, name='fieldmodal'),
    url(r'^fieldsave/(?P<repoid>\d+)/$',views.fieldsave, name='fieldsave'),
    url(r'^fieldeditmodal/(?P<title>\d+)/(?P<pk>\d+)/$', views.fieldeditmodal, name='fieldeditmodal'),
    url(r'^Querymodal/(?P<title>\d+)/$', views.Querymodal, name='Querymodal'),
    url(r'^reportQuerySave/(?P<repoid>\d+)/$',views.reportQuerySave, name='reportQuerySave'),
    url(r'^Queryeditmodal/(?P<title>\d+)/(?P<pk>\d+)/$', views.Queryeditmodal, name='Queryeditmodal'), 
    url(r'^groupmodal/(?P<title>\d+)/$', views.groupmodal, name='groupmodal'),
    url(r'^groupingsave/(?P<repoid>\d+)/$',views.groupingsave, name='groupingsave'),
    url(r'^groupeditmodal/(?P<title>\d+)/(?P<pk>\d+)/$', views.groupeditmodal, name='groupeditmodal'),
    url(r'^delQuery/(?P<title>\d+)/$', views.delQuery, name='delQuery'),
    url(r'^delgroup/(?P<title>\d+)/$', views.delgroup, name='delgroup'),
    url(r'^delfield/(?P<title>\d+)/$', views.delfield, name='delfield'),
    url(r'^delparam/(?P<title>\d+)/$',views.delparam, name='delparam'),    
    url(r'^reportprocess/(?P<title>\d+)/(?P<pk>.*)/$', views.reportprocess, name='reportprocess'),
    url(r'^generatepage/(?P<reportid>\d+)/$', views.generate_reportpage, name='generatepage'),
    url(r'^print_format_config/(?P<title>\d+)/(?P<pk>\d+)/$', views.print_format_config, name='print_format_config'),
    url(r'^add_action_report/(?P<report_id>\d+)/$', views.add_action_report, name='add_action_report'),
    url(r'^pdf_config/(?P<title>\d+)/(?P<pk>\d+)/$',views.report_pdf,name='report_pdf'),
    url(r'^csv_config/(?P<title>\d+)/(?P<pk>\d+)/$',views.report_csv,name='report_csv'),
    url(r'^html_config/(?P<title>\d+)/(?P<pk>\d+)/$',views.report_html,name='report_config'),
    url(r'^report_pdf/(?P<title>\d+)/(?P<pk>\d+)/$',views.report_pdf,name='report_pdf'),
    url(r'^submit_config/(?P<title>\d+)/(?P<pk>\d+)/$',views.report_submit,name='report_submit'),
    url(r'^payment_config/(?P<title>\d+)/(?P<pk>\d+)/$',views.payment,name='payment'),
    url(r'^new_config/(?P<title>\d+)/(?P<pk>\d+)/$',views.newaction,name='newaction'),
    url(r'^del_action/(?P<title>\d+)/(?P<pk>\d+)/$',views.delaction,name='delaction'),
     ]

reportview/models.py
from django.db import models
from django_extensions.db.models import TitleSlugDescriptionModel, \
	TimeStampedModel, TitleDescriptionModel

from master.models import ComponentType, WidgetType
from django.contrib.auth.models import User
from django.db.models.deletion import SET_NULL
from project.models import Project
from printformat.models import PrintFormat
from transactionview.models import Transactionview,Component

VIEW_TYPES = (
	('total','Total',),
	('avg','Average',),
	('percentage','Percentage',),
	)


FILL_COLOR_TYPES = (
	('red','Red',),
	('blue','Blue',),
	('green','Green',),
	('yellow','Yellow',),
	('purple','Purple',),

	)

STROKE_COLOR_TYPES = (
	('red','Red',),
	('blue','Blue',),
	('green','Green',),
	('yellow','Yellow',),
	('purple','Purple',),

	)

GRAPH_TYPES = (
	('column','Column chart',),
	('line','Line chart',),
	('pie','Pie chart',),	
	('bar','Bar chart',),
	('horizontalBar','Horizontal Bar')
	
	
	)

REPORT_TYPES= (

	('onlinereport','OnlineReport'),
	('offlinereport','OfflineReport'),
	('displayreport','Displayreport'),
	('graphicalreport','Graphicalreport')
	)

REPORT_FIELD_TYPES= (
    ('query-field','Query Field'),
    ('expression-field','Expression Field'),
    ) 
    
REPORT_DATA_TYPES = (
	('char','Char'),
	('numeric','Numeric'),
	('datetime','DateTime'),
	('template_column','Template Column'),
	('button','Button')
	)
ALIGNMENT_TYPES = (
	('left','Left'),
	('center','Center'),
	('right','Right'),
	)

BOX_TYPES = (
	('small-panel','Small Panel',),
	('large-panel','Large Panel',),
	('medium-panel','Medium Panel',),
	)

RESULT_JOIN_TYPES = (
	('none','None'),
    ('left-outer-join','Left Outer Join'),
    ('inner-join','Inner Join'),
    ('cross-join','Cross Join'),
    )

TEMPLATE_TYPE_CHOICES=(
	('card','Card'),
	('list','List')
	)

ICON_TYPE_CHOICES =(
	('add','Add'),
	('albums','Albums'),
	('logo-android','Android'),
	('logo-angular','Angular'),
	('aperture','Aperture'),
	('logo-apple','Apple'),
	('apps','Apps'),
	('archive','Archive'),
	('barcode','Barcode'),
	('basket','Basket'),
	('bicycle','Bicycle'),
	('logo-bitcoin','Bitcoin'),
	('bonfire','Bonefire'),
	('book','Book'),
	('bookmark','Bookmark'),
	('bookmarks','Bookmarks'),
	('briefcase','Briefcase'),
	('calculator','Calculator'),
	('calendar','Calendar'),
	('card','Card'),
	('cash','Cash'),
	('clock','Clock'),
	('cloud','Cloud'),
	('codepen','Codepen'),
	('construct','Construct'),
	('contact','Contact'),
	('copy','Copy'),
	('create','Create'),
	('cube','Cube'),
	('desktop','Desktop'),
	('disc','Disc'),
	('document','Document'),
	('flame','Flame'),
	('flower','Flower'),
	('floder','Floder'),
	('globe','Globe'),
	('grid','Grid'),
	('help-buoy','Help-Buoy'),
	('home','Home'),
	('images','Images'),
	('information-circle','Information-Circle'),
	('keypad','Keypad'),
	('laptop','Laptop'),
	('list-box','List-Box'),
	('lock','Lock')
		)    

PRINT_ACTION_TYPE_CHOICES  = (
	('Server','Server'),
	('Client','Client')
)
SQL_TYPE_CHOICES = (
	('Nongrid','Nongrid'),
	('Grid','Grid')
	
)

class Report(TitleDescriptionModel, TimeStampedModel):
	enable_header = models.BooleanField(default=True)
	slug =  models.CharField( max_length=255, blank=True,null=True)
	project = models.ForeignKey(Project, related_name='reportview_projects',blank=True,null=True)
	report_header_line1 = models.CharField( max_length=255, blank=True, null=True)
	report_header_line2 = models.CharField( max_length=255, blank=True, null=True)
	report_footer_line1 = models.CharField( max_length=255, blank=True, null=True)
	report_footer_line2 = models.CharField( max_length=255, blank=True, null=True)
	row_count = models.SmallIntegerField(default=10)
	is_hidden = models.BooleanField(default=False)
	report_type = models.CharField(choices=REPORT_TYPES, max_length=20, blank=True,null=True)
	report_description = models.CharField( max_length=2000, blank=True, null=True)
	lines_per_page = models.PositiveSmallIntegerField(default=0)
	show_grand_total = models.BooleanField(default=False)
	template_type = models.CharField(choices=TEMPLATE_TYPE_CHOICES, max_length=20, blank=True,null=True)
	rowtemplate= models.TextField(blank=True,null=True)
	identifiers = models.CharField(max_length=150,null=True, blank=True)
	dont_repeat_reference_field = models.ForeignKey('ReportField', blank=True,null=True , related_name='+')
	xcoordinates= models.ForeignKey('ReportField', blank=True,null=True , related_name='+')
	ycoordinates= models.ForeignKey('ReportField', blank=True,null=True , related_name='+')
	showxyaxis= models.BooleanField(default=False)
	graphtype=models.CharField(choices=GRAPH_TYPES, max_length=20, blank=True,null=True)
	class Meta:
	    verbose_name = "Report"
	    verbose_name_plural = "Reports"

	def __str__(self):
	    return self.title
    

class Query(TitleDescriptionModel, TimeStampedModel):
	slug = models.CharField( max_length=255, blank=True, null=True)
	report = models.ForeignKey(Report, related_name='report_queries')
	sql = models.TextField()
	is_main_query = models.BooleanField(default=False)
	join_type =  models.CharField(choices=RESULT_JOIN_TYPES, max_length=20 , blank=True,null=True) 

	class Meta:
	    verbose_name = "Query"
	    verbose_name_plural = "Querys"

	def __str__(self):
	    return self.title

class ReportField(TitleDescriptionModel, TimeStampedModel):
	slug =  models.CharField( max_length=255, blank=True,null=True)
	report = models.ForeignKey(Report, related_name='report_fields')
	query = models.ForeignKey(Query , blank=True,null=True,on_delete=SET_NULL)
	caption = models.CharField(max_length=255,null=True)
	data_type = models.CharField(choices=REPORT_DATA_TYPES, max_length=20, blank=True,null=True)
	iconcls = models.CharField(choices=ICON_TYPE_CHOICES,max_length=100,null=True,blank=True)
	no_of_decimal_digits = models.SmallIntegerField(default=0)
	show_running_total = models.BooleanField(default=False)
	show_total = models.BooleanField(default=False)
	is_hidden = models.BooleanField(default=False)
	apply_comma = models.BooleanField(default=False)
	dont_repeat = models.BooleanField(default=False)
	column_alignment = models.CharField(choices=ALIGNMENT_TYPES	, max_length=20,blank=True,null=True)
	dont_show_zero = models.BooleanField(default=False)
	display_order = models.PositiveSmallIntegerField(default=0)
	width = models.PositiveSmallIntegerField(default=0)
	height = models.PositiveSmallIntegerField(default=0)
	iconcls = models.CharField(choices=ICON_TYPE_CHOICES,max_length=100,null=True,blank=True)
	expression = models.TextField(blank=True,null=True)
	validate_expression = models.TextField(blank=True,null=True) 

	class Meta:
	    verbose_name = "ReportField"
	    verbose_name_plural = "ReportFields"

	def __str__(self):
	    return self.title

class ReportParamField(TitleDescriptionModel, TimeStampedModel):
	slug =  models.CharField( max_length=255, blank=True,null=True)
	caption = models.CharField( max_length=255, blank=True, null=True)
	report = models.ForeignKey(Report, related_name='report_params')
	query =  models.ForeignKey(Query, blank=True,null=True,on_delete=SET_NULL)
	display_order = models.PositiveSmallIntegerField(default=0)
	is_hidden = models.BooleanField(default=False)
	no_of_decimal_digits = models.PositiveSmallIntegerField(default=0)
	data_type = models.CharField(choices=REPORT_DATA_TYPES, max_length=20, blank=True,null=True)
	component_type = models.ForeignKey('master.ComponentType' , related_name='+', blank=True,null=True)
	widget_type = models.ForeignKey('master.WidgetType', related_name='+', blank=True,null=True)
	value_field = models.CharField( max_length=100, blank=True,null=True )
	display_field = models.CharField( max_length=100, blank=True,null=True )
	sql = models.TextField( max_length=1000, blank=True,null=True )

	allow_empty = models.BooleanField(default=False)
	expression = models.TextField(blank=True,null=True) 
	expression_postfix = models.TextField(blank=True,null=True)  
	validate_expression = models.TextField(blank=True,null=True)
	validate_expression_postfix = models.TextField(blank=True,null=True)
	identifiers = models.CharField(max_length=150,null=True, blank=True)

	class Meta:
	    verbose_name = "ReportParamField"
	    verbose_name_plural = "ReportParamFields"

	def __str__(self):
	    return self.title



class ReportGrouping(models.Model):
	report = models.ForeignKey(Report, related_name='report_groupings')
	groupby_field = models.ForeignKey(ReportField, blank=True,null=True,on_delete=SET_NULL)
	caption_field = models.ForeignKey(ReportField,blank=True,null=True, related_name='+')
	header_caption_template = models.CharField( max_length=255, blank=True,null=True)
	footer_caption_template = models.CharField( max_length=255, blank=True,null=True)
	show_line_space = models.BooleanField(default=False)
	display_order = models.PositiveSmallIntegerField(default=0)

	class Meta:
	    verbose_name = "ReportGrouping"
	    verbose_name_plural = "ReportGroupings"

	def __str__(self):
	    return str(self.id)
	    

class ReportAction(TitleDescriptionModel):
	report = models.ForeignKey(Report, related_name='report_actions',blank=True,null=True)
	report_action = models.CharField(max_length=50,blank=True,null=True)
	order = models.DecimalField(max_digits=5, decimal_places=2, default=0)

	class Meta:
	    verbose_name = "ReportAction"
	    verbose_name_plural = "ReportActions"

	def __str__(self):
	    return self.title


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'static/ionicmeta/{0}/mustachehtml/{1}'.format(instance.project.slug,filename)


class ReportPrintFormatAction(TitleDescriptionModel):

	report_action = models.ForeignKey(ReportAction,blank=True,null=True,related_name='print_formats')
	pfconfig =  models.ForeignKey(PrintFormat,on_delete=models.SET_NULL,blank=True,null=True)
	# click_event = models.CharField(max_length = 1000,blank=True,null=True)
	
	class Meta:
		verbose_name = "PrintFormatAction"
		verbose_name_plural = "PrintFormatActions"

reportview/templates/actions.html
<div class="modal fade" id="repoactionbody" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>
<h3 class="box-title"> Add Actions </h3>

<form method="POST" >
<form method="POST" id="grouping" action="/reportview/groupingsave/{{report.id}}/">
    {% csrf_token %}

    <div class="modal-body" style="height: auto;">

        {{ form.non_field_errors }}
        <div id="loading" style="display: none;">
            <span id="load_text">loading...</span>
        </div>
        <div id="report_add_form_ajax" style="display: none;">
            <span>Form submit successfully</span>
        </div>

        <div id="form_ajax_error" style="display: none;">
            <span>cannot submit data due to errors</span>
        </div>

        <input class="btn btn-success pull-right" type="submit" value="Submit" style="margin-left: 5px;" />

        <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">Cancel</button>
        <br>
        <br>


<label> <input type="checkbox" name="Open_Tx_From_Report" >Open_Tx_From_Report</label>
<br/>
<label> <input type="checkbox" name="Contextmenu" >Contextmenu</label>
<br/>
<label> <input type="checkbox" name="Double_Click" >Double_Click</label>
<br/>
<label> <input type="checkbox" name="Mail" >Mail</label>
<br/>
<label> <input type="checkbox" name="Sms" >Sms</label>
<br/>
<label> <input type="checkbox" name="Print_Format" >Print_Format</label>
<br/>
<label> <input type="checkbox" name="CustomAction" >CustomAction</label>
<br/>
<label> <input type="checkbox" name="InlineButtonAction" >InlineButtonAction</label>
 
</form>

reportview/templates/bredit.html
<div class="modal fade" id="BRbody" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
<h3 class="modal-title" id="lineModalLabel">Edit Report Business Rule</h3>
<form method="POST" id="breditform" action="/reportview/BRedit/{{title}}/{{report_br.id}}/">
   {% csrf_token %}
   <div class="modal-body">
      <div class="row">
         <div class="col-md-12 col-lg-12">
            {{ form.non_field_errors }}
            <div id="loading" style="display:none;">
               <span id="load_text">loading...</span>
            </div>
            <div id="report_add_form_ajax" style="display:none;">
               <span>Form submit successfully.</span>
            </div>
            <div id="form_ajax_error" style="display:none;">
               <span>Can not submit data due to errors.</span>
            </div>
           
            <div>
               <button type="button" class="btn btn-danger pull-right" data-dismiss="modal" style="margin-left: 5px;">Cancel</button>
               <input class="btn btn-success pull-right" type="submit" value="Submit" ></input>
            </div>
            <br/>
            <br/>
            <div class="tab-v2">
               <ul class="nav nav-tabs">
                  <li><a href="#business_rule" data-toggle="tab">Business Rule</a></li>
                  <li><a href="#sql" data-toggle="tab">sql</a></li>
                  <!-- <li><a href="#graphical_report" data-toggle="tab">  Graphical Report</a></li>
                     <li><a href="#box_report" data-toggle="tab">Box Report</a></li>-->
               </ul>
               <div class="tab-content">
                  <div class="tab-pane fade in active" id="business_rule">
                     <div class="row">
                        <div class="col-md-6">
                           <label>Title <span class="asteriskField">*</span></label>
                           <input class="form-control" style="width:100%" name="businesstitle" value="{{ report_br.title }}"></input>
                           <label>Report param field</label>
                           
                            {{form.report_param_field}}
                           
                           <label>Report field</label>
                           
                           {{form.report_field}}
                           
                           <label>Validate expression <span class="asteriskField">*</span></label>
                           <input class="form-control" style="width:100%" name="validate_expression" value="{{ report_br.min_filter_chars }}"></input>
                           <label>Description</label>
                           <textarea class="form-control" style="width:100%" name="description"></textarea>
                        </div>
                        <div class="col-md-6">
                           <label>Expression</label>
                           <input class="form-control" style="width:100%" name="expression" value="{{ report_br.expression }}"></input>
                           <label>Display format expression</label>
                           <input class="form-control" style="width:100%" name="display_format_expression" value="{{ report_br.display_format_expression }}"></input>
                          
                        </div>
                     </div>
                  </div>
                  <div class="tab-pane fade in" id="sql">
                     <div class="row">
                        <div class="col-md-12">
                           <label>Sql*</label>
                           <br/>
                           <label for="sql_comp_id">Components:</label>
      <select class="form-control" id="sql_comp_id" style="width:100%" onclick="sqlCompFunction()">
         <option selected="selected" value="" >----------</option>
         {% for comp in comp_list %}
               <option id={{comp.id }} value={{comp.title}} data-desc={{comp.description}} >{{ comp.title}}</option>
          {% endfor %}
      </select>
      <br>
       <textarea class="form-control" style="width:100%" id="id_sql" name="sql" ></textarea>
                        </div>
                         <div class="col-md-6">
                            <div class="row">
                           <label>
                            <input type="checkbox" name="enable_filter" value="{{ report_br.enable_filter }}">Enablefilter</label>
                           <br/>
                           <label>Result chunk size</label>
                            <input class="form-control" style="width:100%" name="result_chunk_size" value="{{ report_br.result_chunk_size }}"></input>
                        </div>
                         </div>
                          <div class="col-md-6">
                            <div class="row">
                           
                           <label>Min filter chars</label>
                            <input class="form-control" style="width:100%" name="min_filter_chars"  value="{{ report_br.min_filter_chars }}" ></input>
                        </div>
                         </div>

                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</form>

reportview/templates/businessrule.html
<div class="modal fade" id="BRbody" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
<h3 class="modal-title" id="lineModalLabel">Report Business Rule</h3>
<form method="POST" id="brform" action="/reportview/brsave/{{BR.id}}/">
   {% csrf_token %}
   <div class="modal-body">
      <div class="row">
         <div class="col-md-12 col-lg-12">
            {{ form.non_field_errors }}
            <div id="loading" style="display:none;">
               <span id="load_text">loading...</span>
            </div>
            <div id="report_add_form_ajax" style="display:none;">
               <span>Form submit successfully.</span>
            </div>
            <div id="form_ajax_error" style="display:none;">
               <span>Can not submit data due to errors.</span>
            </div>
            <input type="hidden" id="brsave" value="{{BR.id}}">
            <div>
               <button type="button" class="btn btn-danger pull-right" data-dismiss="modal" style="margin-left: 5px;">Cancel</button>
               <input class="btn btn-success pull-right" type="submit" value="Submit" ></input>
            </div>
            <br/>
            <br/>
            <div class="tab-v2">
               <ul class="nav nav-tabs">
                  <li><a href="#business_rule" data-toggle="tab">Business Rule</a></li>
                  <li><a href="#sql" data-toggle="tab">sql</a></li>
                  <!-- <li><a href="#graphical_report" data-toggle="tab">  Graphical Report</a></li>
                     <li><a href="#box_report" data-toggle="tab">Box Report</a></li>-->
               </ul>
               <div class="tab-content">
                  <div class="tab-pane fade in active" id="business_rule">
                     <div class="row">
                        <div class="col-md-6">
                           <label>Title <span class="asteriskField">*</span></label>
                           <input class="form-control" style="width:100%" name="businesstitle"></input>
                           <label>Report param field</label>
                           
                            {{form.report_param_field}}
                           
                           <label>Report field</label>
                           
                           {{form.report_field}}
                           
                           <label>Validate expression <span class="asteriskField">*</span></label>
                           <input class="form-control" style="width:100%" name="min_filter_chars"></input>
                           <label>Description</label>
                           <textarea class="form-control" style="width:100%" name="description"></textarea>
                        </div>
                        <div class="col-md-6">
                           <label>Expression</label>
                           <input class="form-control" style="width:100%" name="expression"></input>
                           <label>Display format expression</label>
                           <input class="form-control" style="width:100%" name="display_format_expression"></input>
                          
                        </div>
                     </div>
                  </div>
                  <div class="tab-pane fade in" id="sql">
                     <div class="row">
                        <div class="col-md-12">
                           <label>Sql*</label>
                           <br/>
                          <label for="sql_comp_id">Components:</label>
      <select class="form-control" id="sql_comp_id" style="width:100%" onclick="sqlCompFunction()">
         <option selected="selected" value="" >----------</option>
         {% for comp in comp_list %}
               <option id={{comp.id }} value={{comp.title}} data-desc={{comp.description}} >{{ comp.title}}</option>
          {% endfor %}
      </select>
      <br>
       <textarea class="form-control" style="width:100%" id="id_sql" name="sql" ></textarea>
                        </div>
                         <div class="col-md-6">
                            <div class="row">
                           <label>
                            <input type="checkbox" name="Enable filter" value="{{ field.apply_comma }}">Enablefilter</label>
                           <br/>
                           <label>Result chunk size</label>
                            <input class="form-control" style="width:100%" name="result_chunk_size"></input>
                        </div>
                         </div>
                          <div class="col-md-6">
                            <div class="row">
                           
                           <label>Min filter chars</label>
                            <input class="form-control" style="width:100%" name="min_filter_chars"></input>
                        </div>
                         </div>

                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</form>

reportview/templates/reportactions.html
<div class="modal fade" id="actionbody" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>
<!-- <h3 class="box-title"> Add Actions </h3> -->
<div>
<form id="actionForm"  method="POST" action ="/reportview/add_action_report/{{report_id}}/" >

  {% csrf_token %}
        <div class="row">
            <div class="col-md-6 col-lg-6">
                {{ form.non_field_errors }}
               <div>
                    <!-- <div>
                        <input type="radio" id="select_all">
                    </div> -->
                    <div id="form_id">{{form.report_action}}</div>
                </div>
                <input type="hidden" name= "order" value="0" />
               
            </div>
        </div>


<!--<input type="hidden" id="id_Action_Type" value="{{typeid.id}}">-->
 <input class="btn btn-success pull-right" type="submit" value="Submit" style="margin-left: 5px;">

 <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">Cancel</button>
 <br><br>
</form>
</div>

 <script>
  $(function () {
    $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
      checkboxClass: 'icheckbox_flat-blue',
      radioClass   : 'iradio_flat-green'
    })
  });
  </script>