Mobilebuilder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from index import views as index_views
from authentication import views as authen_views
from django.contrib.auth import views as auth_views
from transaction import views as trans_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('index.urls')), 
    url(r'^authentication/', include('authentication.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^usersetup/', include('usersetup.urls')),
    url(r'^project/',include('project.urls')),
    url(r'^transaction/', include('transaction.urls')),
    url(r'^schema/',include('schema.urls')),
    url(r'^transactionview/',include('transactionview.urls')),
    url(r'^logintemplate/',include('logintemplate.urls')),
    url(r'^hometemplate/',include('hometemplate.urls')),
    url(r'^actions/',include('actions.urls')),
    url(r'^reportview/',include('reportview.urls')),
    url(r'^syncmaster/',include('syncmaster.urls')),
    url(r'^generateprocess/',include('generateprocess.urls')),
    url(r'^login/',authen_views.login,name='login'),
    url(r'^$', index_views.base, name='base'),
    url(r'^signout/', index_views.signout, name='signout'),
    url(r'^transindex/',trans_views.transindex, name='transindex'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^favicon.ico$',RedirectView.as_view(url='/static/maincss/images/user.png')),
    url(r'^rolesetup/',include('rolesetup.urls')),
    url(r'^smssetup/',include('smssetup.urls')),
    url(r'^notification/',include('notification.urls')),
    url(r'^printformat/',include('printformat.urls')),
    url(r'^eventconfiguration/',include('eventconfiguration.urls'))
]

home/urls.py
from django.conf.urls import include, url
from . import views


app_name ='home'
urlpatterns = [
	url(r'^main/', views.main, name='main'),
		]

project/urls.py
from django.conf.urls import url
from .views import projectindex,projectcreation,pdelete,pedit,getin,setUserInDB,editUserInDB,saveUserInDB,deleteUserInDB,createIonic,ionicProject,alreadyIonic,ionicPlatform,ionicPlugin,ionicService,ionicBuild,ionicPages,ionicapk,apkdownload,theming,ionicsplash,generatesplash,dbtosql,ionicNotify,resetapp,ionicSMSSave,emailConfig,googleAPISetup,fontfile,fontfile_delete,geolocation,geolocationplugins,deleteapp

urlpatterns = [
    url(r'^projectindex/$', projectindex, name='projectindex'),
    url(r'^projectcreation/$', projectcreation, name='projectcreation'),
    url(r'^pdelete/(?P<projectid>.*)$', pdelete, name='pdelete'),
    url(r'^pedit/(?P<projectid>.*)$', pedit, name='pedit'),
    url(r'^getin/(?P<projectid>.*)$', getin, name='getin'),
    url(r'^setUserInDB/$', setUserInDB, name='setUserInDB'),
    url(r'^editUserInDB/(?P<transactionid>\d+)$', editUserInDB, name='editUserInDB'),
    url(r'^saveUserInDB/$', saveUserInDB, name='saveUserInDB'),
    url(r'^deleteUserInDB/(?P<projectwiseusersetupid>\d+)$', deleteUserInDB, name='deleteUserInDB'),
    url(r'^createIonic/(?P<projectid>.*)$', createIonic, name='createIonic'),
    url(r'^ionicProject/(?P<projectid>.*)$', ionicProject, name='ionicProject'),
    url(r'^alreadyIonic/(?P<projectid>.*)$', alreadyIonic, name='alreadyIonic'),
    url(r'^ionicPlatform/(?P<projectid>.*)$', ionicPlatform, name='ionicPlatform'),
    url(r'^ionicPlugin/(?P<projectid>.*)$', ionicPlugin, name='ionicPlugin'),
    url(r'^ionicService/(?P<projectid>.*)$', ionicService, name='ionicService'),
    url(r'^ionicNotify/(?P<projectid>.*)$', ionicNotify, name='ionicNotify'),
    url(r'^ionicSMSSave/(?P<projectid>.*)$', ionicSMSSave, name='ionicSMSSave'),
    url(r'^emailConfig/(?P<projectid>.*)$', emailConfig, name='emailConfig'),
    url(r'^ionicBuild/(?P<projectid>.*)$', ionicBuild, name='ionicBuild'),
    url(r'^ionicPages/(?P<projectid>.*)$', ionicPages, name='ionicPages'),
    url(r'^ionicapk/(?P<projectid>.*)$', ionicapk, name='ionicapk'),
    url(r'^apkdownload/(?P<projectid>.*)$', apkdownload, name='apkdownload'),
    url(r'^theming/(?P<projectid>.*)$', theming, name='theming'),
    url(r'^ionicsplash/(?P<projectid>.*)$', ionicsplash, name='ionicsplash'),
    url(r'^fontfile/(?P<projectid>.*)$', fontfile, name='fontfile'),
    url(r'^fontfile_delete/(?P<projectid>.*)$', fontfile_delete, name='fontfile_delete'),
    url(r'^generatesplash/(?P<projectid>.*)$', generatesplash, name='generatesplash'),
    url(r'^dbtosql/$', dbtosql, name='dbtosql'),
    url(r'^resetApp/(?P<projectid>.*)$', resetapp, name='resetapp'),
    url(r'^googleAPISetup/(?P<projectid>.*)$', googleAPISetup, name='googleAPISetup'),
    url(r'^geolocation/(?P<projectid>.*)$', geolocation, name='geolocation'),
    url(r'^geolocationplugins/(?P<projectid>.*)$', geolocationplugins, name='geolocationplugins'),
    url(r'^deleteapp/(?P<projectid>.*)$', deleteapp, name='deleteapp'),
]

project/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from authentication.models import userprofile
from schema.models import Db_profile
from django_extensions.db.models import TimeStampedModel

# Create your models here.
PROJECT_TYPE_CHOICES = (
        ('ecommerce','E-Commerce'),
        ('business','Business'),
    )

PROTOCOL_TYPE_CHOICES = (
        ('http://','HTTP'),
        ('https://','HTTPS'),
    )
    
APPLICATION_TYPE_CHOICES = (
    ('android','Android'),
    ('iOS','iOS'),
    ('windows','Windows')
)

DB_TYPE_CHOICES = (
        ('new','new'),
		('edited','edited'),
        ('updated','updated'),
		('deleted','deleted')
)

TIME_TYPE_CHOICES = (
   ('1800000','30 Minutes'),
   ('900000','15 Minutes'),
   ('600000','10 Minutes'),
)

TRACKING_TYPE_CHOICES = (
  ('true','Yes'),
  ('false','No')
)

class Project(TimeStampedModel,models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)    
    ptype = models.CharField(max_length=50, choices=PROJECT_TYPE_CHOICES)
    application_type = models.CharField(max_length=50, choices=APPLICATION_TYPE_CHOICES)
    admin_id = models.ForeignKey(userprofile, on_delete=models.CASCADE)
    prmcolor = models.CharField(max_length=100,null=True, blank=True ,default="#488aff")    
    seccolor = models.CharField(max_length=100,null=True, blank=True,default="#32db64")
    dark = models.CharField(max_length=100,null=True, blank=True,default="#000000")
    slug = models.CharField(max_length=150,null=True, blank=True)
    table_append_by_underscore = models.BooleanField(default=False)
    ismultitenant = models.BooleanField(default=False)
    imei_based_login = models.BooleanField(default=False)
    # projectid = models.CharField(max_length=100)
	
    def __str__(self):
        return self.title

class Projectwiseusersetup(TimeStampedModel,models.Model):
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    userid = models.ForeignKey(userprofile, on_delete=models.CASCADE)
    db_profileid = models.ForeignKey(Db_profile, on_delete=models.CASCADE)
    setasdefaultproject = models.BooleanField(default=False)

    def __str__(self):
        return self.project_id.title

class IonicProjectConfig(TimeStampedModel,models.Model):
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    itype = models.CharField(max_length=100,null=True, blank=True)
    platform = models.CharField(max_length=100,null=True, blank=True)
    plugin = models.CharField(max_length=200,null=True, blank=True)
    providers = models.CharField(max_length=200,null=True, blank=True)
    

class IonicImages(TimeStampedModel,models.Model):
    splashimg = models.FileField(upload_to = 'static/ionicsrc/images/splash',null=True, blank=True)
    iconimg =   models.FileField(upload_to = 'static/ionicsrc/images/icon',null=True, blank=True)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)

class IonicFonts(TimeStampedModel,models.Model):
    fontname = models.CharField(max_length=100,null=True, blank=True)
    fontfile =   models.FileField(upload_to = 'static/ionicsrc/images/fonts',null=True, blank=True)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)

class IonicServices(TimeStampedModel,models.Model):
    protocol = models.CharField(max_length=50,choices=PROTOCOL_TYPE_CHOICES)
    host = models.CharField(max_length=200,null=True, blank=True)
    port = models.CharField(max_length=200,null=True, blank=True)
    context = models.CharField(max_length=200,null=True, blank=True)
    serviceurl = models.CharField(max_length=200,null=True, blank=True)
    basicid = models.CharField(max_length=100,null=True, blank=True)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)

class IonicNotification(TimeStampedModel,models.Model):
    apikey = models.CharField(max_length=200,null=True, blank=True)
    senderid = models.CharField(max_length=200,null=True, blank=True)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)     

class GoogleAPISetup(TimeStampedModel,models.Model):
    apikey = models.CharField(max_length=200,null=True, blank=True)
    clientid = models.CharField(max_length=200,null=True, blank=True)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)

class GeolocationSetup(TimeStampedModel,models.Model):
    tracking = models.CharField(max_length=50, choices=TRACKING_TYPE_CHOICES)
    time_interval = models.CharField(max_length=50, choices=TIME_TYPE_CHOICES)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)

class EmailConfiguration(TimeStampedModel,models.Model):
    server = models.CharField(max_length=50,null=True,blank=True)
    port = models.BigIntegerField(null=True,blank=True)
    email_id = models.CharField(max_length=50,null=True,blank=True)
    pwd = models.CharField(max_length=50,null=True,blank=True)
    Domain = models.CharField(max_length=50,null=True,blank=True)
    default_email_id = models.CharField(max_length=200,null=True, blank=True)
    protocol = models.CharField(max_length=200,null=True, blank=True)
    is_aunthentication_req  = models.BooleanField(default=False)
    support_tls = models.BooleanField(default=False)
    db_status = models.CharField(max_length=250, choices=DB_TYPE_CHOICES)
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)   

project/forms.py
from django import forms 
from django.forms import ModelForm
from .models import Project, Projectwiseusersetup,IonicProjectConfig,IonicImages,IonicFonts,IonicServices,IonicNotification,EmailConfiguration,GoogleAPISetup,GeolocationSetup


    
class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title','description','ptype','application_type','table_append_by_underscore','ismultitenant','imei_based_login']
        exclude = ['admin_id','prmcolor','seccolor']
        
class ProjectwiseusersetupForm(ModelForm):
    class Meta:
        model = Projectwiseusersetup
        fields = ['project_id','userid','db_profileid','setasdefaultproject']

class IonicProjectConfigForm(ModelForm):
    class Meta:
        model = IonicProjectConfig
        fields = ['project_id','itype','platform','plugin','providers']

class IonicImagesForm(ModelForm):
    class Meta:
        model = IonicImages
        fields =['splashimg','iconimg']
        exclude = ['project_id']

class IonicFontsForm(ModelForm):
    class Meta:
        model = IonicFonts
        fields =['fontname','fontfile']
        exclude = ['project_id']

class IonicServicesForm(ModelForm):
    class Meta:
        model = IonicServices
        fields =['protocol','host','port','context','basicid']
        exclude = ['serviceurl','project_id']

class IonicNotificationForm(ModelForm):
    class Meta:
        model = IonicNotification
        fields =['apikey','senderid']
        exclude = ['project_id']

class GoogleAPISetupForm(ModelForm):
    class Meta:
        model = GoogleAPISetup
        fields =['apikey','clientid']
        exclude = ['project_id']

class GeolocationSetupForm(ModelForm):
    class Meta:
        model = GeolocationSetup
        fields ='__all__'
        exclude = ['project_id']

class EmailConfigurationForm(ModelForm):
    class Meta:
        model = EmailConfiguration
        fields ='__all__'
        exclude = ['project_id','db_status']        

project/templates/edit.html
<div class="modal fade" id="mymodalbody" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
</div>
<div id="errorDiv5" style="font-size:20px" > </div>

<form id="form" method="POST">
    {% csrf_token %}
    <input type="hidden" name="tableid" value="{{transactionid}}">
    <div class="form-group">
        <label for="pname"> Project Name </label>
        <input type="text" readonly class="form-control" id="pname" name="project_id" value="{{recvid}}">
    </div>
    <div class="form-group">
        <label> Select User </label>
        {{ form.userid }}
        <!-- <select  required id="userlist" name="userid" >
            <option value="{{cur_usr}}" selected> {{recvid.userid}} </option>
            {% if users %}
                {% for user in users %}
                    <option value="{{user.id}}">
                        {{user.email}} 
                    </option>
                {% endfor %}
            {% endif %}
        </select>  -->
       
    </div>
    <div class="form-group">
        <label for="exampleInputadmindb">Data base</label>
        {{ form.db_profileid }}
    </div>
    <div class="form-group">
        <label for="pname"> Set as Default Project </label>
        <label class="switch1">
            {{form.setasdefaultproject}}
            <div class="slider round">
            </div>
        </label>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="sumbit" class="sss btn btn-success" id="save_btn">Save</button>
        </div>
</form>

<script type ='text/javascript'>
		$('#save_btn').on('click',function(e){
			debugger;

			var frm = $("form");
			$.ajax({
					type : 'post',
					url : '/project/saveUserInDB/',
					data : frm.serialize(),
					//dataType: 'json',				 
					success : function (data) {
						debugger;
						if(data.split(":-:")[1]=="0"){
							$("#errorDiv5").text(data.split(":-:")[0]).css("color","green");
							
						}else if(data.split(":-:")[1]=="2"){
							$("#errorDiv5").text(data.split(":-:")[0]).css("color","red");
							
							
						}
						else if(data.split(":-:")[1]=="1"){

							$("#errorDiv5").text(data.split(":-:")[0]);
							
						}
					},
					failure : function (data) {
						alert('An error occurred.');
                		console.log(data);
				}
			});
		});
</script>

project/templates/getin.html
{% extends 'main.html' %}
{% load static %}
{% block toolbar %}
<li>
    <a href="#" data-toggle="control-sidebar">{{ptitle}}</a>
  </li>
  <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Switch Project
            <ul class="dropdown-menu">
                <!-- inner menu: contains the actual data -->
                 <li class="dropdown-item" style="height:45px;padding: 10px;text-align: center;">
                <h4>Avaliable Projects</h4>
              </li>
                {% if projectselect %}
                {% for selection in projectselect %}
                  <li class="header">
                    <a href="/project/getin/{{selection.id}}">
                      <h4>
                        <img src="{% static 'maincss/img/folder.png' %}" class="img-circle" alt="User Image" />
                           &nbsp;  &nbsp;&nbsp;
                           {{selection.title}}
                      </h4>
                    </a>
                  </li>
                  {% endfor %}
                  {% endif %}
                </ul></a>
              </li>
{% endblock toolbar %}
{% block adminmenu %}
<!-- sidebar menu: : style can be found in sidebar.less -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
          <li class="treeview">
          <a href="/usersetup/userindex/">
            <i class="fa fa-user-plus"></i> <span>User Setup</span>
            <span class="pull-right-container">
            <!--    <i class="fa fa-angle-left pull-right"></i> -->
            </span>
          </a>
        <li class="active treeview">
          <a href="/project/projectindex/">
            <i class="fa fa-folder"></i>
            <span>Project Setup</span>
            <span class="pull-right-container">
            </span>
          </a>
        </li>
        <li class="treeview">
          <a href="/schema/config/">
            <i class="fa fa-database"></i> <span>DB Setup</span>
            <span class="pull-right-container">
            </span>
          </a>
        </li >
        <li class="treeview" id ="createIoniclb">
          <a href ="/project/ionicProject/{{currentProject}}" id="createIonic" name="createIonic" data-projectid = {{currentProject}}>
            <i class="fa fa-android"></i> <span>Ionic Project Create</span>
            <span class="pull-right-container">
            </span>
          </a>
        </li>
        </li>
        </ul>
<!-- /.sidebar -->
{% endblock adminmenu %}
{% block contentmain %}
<section class="content-header">
   <h1>
      Project Configuration
   </h1>
   <ol class="breadcrumb">
      <li><a href="/home/main/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Project Configuration</li>
   </ol>
</section>
<section class="content" >
   <div class="row">
      <div class="col-md-12">
         <div class="box box-primary">
            <div class="box-header with-border">
               <h3 class="box-title">Edit the following Informations</h3>
            </div>
            <div id="errorDiv2" style="color:red;font-size:20px"> </div>
            <div id="errorDiv1" style="color:green;font-size:20px"> </div>
            <form action="" method="POST" >
                {% csrf_token %}
                <div class="box-body">
                   <!-- Assinging Project and databse to User -->
                    <div class="form-group">
                        <label for="pname"> Project Name </label>
                        <input type="text" readonly class="form-control" id="pname" name="title" value="{{ form.title.value|default_if_none:'' }}">
                    </div>
                    
                    <div class="form-group">
                        <label for="user">Select User</label> 
                         <select  required id="userlist" >
                            <option value="----"> --------- </option>
                            {% if users %}
                                {% for user in users %}
                                    <option value="{{user.id}}">
                                        {{user.email}} 
                                    </option>
                                {% endfor %}
                            {% endif %}
                        </select> 
                        
                    </div>
                    
                    <div class="form-group">
                        <label for="db"> Select DataBase </label> 
                        {{ tform.db_profileid }}
                    </div>
                    
                    <div class="form-group">
                        <label for="defaultproject">Is Default Project</label>
                        <label class="switch">
                            {{tform.setasdefaultproject}}
                            <div class="slider round">
                            </div>
                        </label>
                    </div>
                    
                    <div class="box-footer">
                        <!--  <button type="submit" class="btn btn-default">Cancel</button> -->
                        <button type="button" id="abc"  value="add" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
         </div>
      </div>
   </div>
</section>
<section class="content">
   <div class="row">
      <div class="col-xs-12">
         <div class="box">
            <div class="box-header">
               <div class="col-lg-10 col-xs-2">
                  <h3 class="box-title">Projectwise User Setup</h3>
               </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-sm-12">
               <table id="conntable"  class="table table-bordered table-hover datatable" style="border:1px solid lightblue">
                  <thead>
                     <tr class="bg-green">
                        <th> id </th>
                        <th> Project Id  </th>
                        <th> User Id </th>
                        <th> DB Profile </th>
                        <th> asDefault </th>
                        <th> Edit </th>
                        <th> Remove </th>
                     </tr>
                  </thead>
                  <tbody>
                     {% for obj in objs %}
                     <tr>
                        <td class="id"> {{obj.id}} </td>
                        <td class="projectDbId">{{obj.project_id}}</td>
                        <td class="UserDbId">{{obj.userid}}</td>
                        <td class="profId">{{obj.db_profileid}} </td>
                        <td>{{obj.setasdefaultproject}} </td>
                        <td> <button type="button" class="btn bg-olive btn-xs bbb" data-toggle="modal" data-backdrop="static" data-keyboard="false" value="Edit" data-target="aaModal" id="edit_button" data-transactionid={{obj.id}}><i class="glyphicon glyphicon-pencil"></i></button>
                        </td>
                        <td class="removeid"> <a href="/project/deleteUserInDB/{{obj.id}}" data-confirm="Are you sure you want to delete?"><button type="button" class="btn btn-danger btn-xs" id="delete_button1" value="Delete" ><i class="glyphicon glyphicon-trash"></i></button></i>
                           </button> </a> 
                        </td>
                     </tr>
                     {% endfor %}
                  </tbody>
               </table>
             </div>
           </div>
            </div>
            <!-- /.box-body -->
         </div>
         <!-- /.box -->
      </div>
      <!-- /.col -->
   </div>
   <!-- /.row -->
</section>
<div class="modal fade" id="aaModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel1" aria-hidden="true">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h3 class="modal-title" id="lineModalLabel">db_profile_info</h3>
         </div>
         <div class="modal-body" id="mymodalbody">
            <!-- content goes here -->
         </div>
      </div>
   </div>
</div>
<!-- jQuery 2.2.3 -->
<script src="{% static 'maincss/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'maincss/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"> </script>

<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

<script type ='text/javascript'>
   $('#abc').on('click',function(e){
   	debugger;
   	var a = "False";
   	if($( "#id_setasdefaultproject").is(":checked")){
   		a = "True";
   	}
   	else{
   		a = "False";
   	}
   	var userid = $('#userlist').find(":selected").val()
   	var dbid = $('#id_db_profileid').find(":selected").val()
   	var pid = $('#pname').val() 
   	
   	var sample = {
   		pname : pid,
   		u_id : userid,
   		db_id : dbid,
   		chkbox : a,
   	};
   	
   	$.ajax({
   		type : 'post',
   		url : '/project/setUserInDB/',
   		data : sample,
   		//dataType: 'json',				 
   		success : function (data) {
   			debugger;
   			if(data.split(":-:")[1]=="0"){
   				$("#errorDiv1").text(data.split(":-:")[0]);
   				setTimeout(function(){
   					location.reload();	
   				},3000);
   			}
   			else{
   				$("#errorDiv2").text(data.split(":-:")[0]);
   				setTimeout(function(){
   					location.reload();	
   				},3000);
   					
   			}
   		},
   		failure : function (data) {
   			debugger;
   			console.log(data)
   		}
   	});
   });
   
$(document).on('click', '.bbb',function(e) {   
// $('').click(function(e){
    debugger;
    var transactionid = e.currentTarget.attributes['data-transactionid'].value
    var dpcon= '/project/editUserInDB/'+transactionid;
    var model = null;
    $("#aaModal").on("shown.bs.modal",function() { 
        debugger;
        setTimeout(function() {
            if (model == null) {    
                model = $.ajax(dpcon)
                    .done(function(data) {
                        $("#mymodalbody").html(data);
                    })
                    .fail(function() {
                        alert("error");
                    });
            }
        },500);  
            
        
    }); 

    $('#aaModal').on('hidden.bs.modal', function(e) {
        console.log("Modal hidden");
        $('#mymodalbody').modal('hide');
        $(this).data('modal', null);
        $("#mymodalbody").html("");
    });
    $("#aaModal").modal('show'); 
    

});
   
    $(document).ready(function() {
        $('a[data-confirm]').click(function(ev) {
            debugger;
            var href = $(this).attr('href');
            if (!$('#dataConfirmModal').length) {
                $('body').append('<div id="dataConfirmModal" class="modal fade" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">Please Confirm</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button><a class="btn btn-primary" id="dataConfirmOK">OK</a></div></div></div></div>');
            }
            $('#dataConfirmModal').find('.modal-body').text($(this).attr('data-confirm'));
            $('#dataConfirmOK').attr('href', href);
            $('#dataConfirmModal').modal({
                show: true
            });
            return false;
        });
    });

   $(document).ready(function() {
      debugger;
      var event = document.getElementsByName('createIonic');
      projectid = event[0].dataset['projectid']
      $.ajax({
         type : 'get',
         url : '/project/alreadyIonic/'+projectid,
         //data : sample,
         //dataType: 'json',            
         success : function (data) {
            if (data == "exist" || data =="Platform exist"){
               $("#createIonic").unbind("click");
               $("#createIoniclb").css('background','white');
               $("#createIoniclb").css('border','1px solid green');
               $('#createIonic').css('color','green');
            }
         }
      });

   });
</script>
{% endblock contentmain %}

project/templates/smsAttrTable.html
<table class="table table-striped table-bordered" id="smsAttrTable">
    <thead class="bg-green">
        <tr>
            <th>Key</th>
            <th>Value</th>
            <th> Disply Order </th>
            <th>Delete</th>  
        </tr>
    </thead>
    <tbody>  
        {{ formset.management_form }}
        {% for form in formset %}
            {{form.id}} 
            <tr>
                <td>{{form.key}}</td>
                <td>{{form.value}}</td>
                <td>{{form.do}}</td>
                
                {% if formset.can_delete %}
                    <td> {{form.DELETE}}</td>
                {% else %}
                    <td></td>                                    
                {% endif %}   
            </tr>
        {% endfor %}
    </tbody>
</table>


 <script type="text/javascript">
  $(function() {
    $('#smsAttrTable tbody > tr').formset({
      prefix: '{{ formset.prefix }}',
      deleteText:'<i class="fa fa-trash" style="color:red;"></i>',
      addText:'<i class="fa fa-plus">Add</i>'
    });
  })


</script> 