Mobilebuilder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from index import views as index_views
from authentication import views as authen_views
from django.contrib.auth import views as auth_views
from transaction import views as trans_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('index.urls')), 
    url(r'^authentication/', include('authentication.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^usersetup/', include('usersetup.urls')),
    url(r'^project/',include('project.urls')),
    url(r'^transaction/', include('transaction.urls')),
    url(r'^schema/',include('schema.urls')),
    url(r'^transactionview/',include('transactionview.urls')),
    url(r'^logintemplate/',include('logintemplate.urls')),
    url(r'^hometemplate/',include('hometemplate.urls')),
    url(r'^actions/',include('actions.urls')),
    url(r'^reportview/',include('reportview.urls')),
    url(r'^syncmaster/',include('syncmaster.urls')),
    url(r'^generateprocess/',include('generateprocess.urls')),
    url(r'^login/',authen_views.login,name='login'),
    url(r'^$', index_views.base, name='base'),
    url(r'^signout/', index_views.signout, name='signout'),
    url(r'^transindex/',trans_views.transindex, name='transindex'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^favicon.ico$',RedirectView.as_view(url='/static/maincss/images/user.png')),
    url(r'^rolesetup/',include('rolesetup.urls')),
    url(r'^smssetup/',include('smssetup.urls')),
    url(r'^notification/',include('notification.urls')),
    url(r'^printformat/',include('printformat.urls')),
    url(r'^eventconfiguration/',include('eventconfiguration.urls'))
]

home/urls.py
from django.conf.urls import include, url
from . import views


app_name ='home'
urlpatterns = [
	url(r'^main/', views.main, name='main'),
		]

printformat/urls.py
from django.conf.urls import url
from . import views


app_name = 'printformat'
urlpatterns = [
    url(r'^printformatindex/$', views.printformatindex, name='printformatindex'),
    url(r'^addPFModal/$', views.addNewFormat, name='addNewFormat'),
    url(r'^savePF/$', views.addNewFormat, name='addNewFormat'),
    url(r'^editPF/(?P<id>\d+)$', views.updtaePFFormat, name='updtaePFFormat'),
    url(r'^deletepf/(?P<id>\d+)$', views.deletePFFormat, name='deletePFFormat'),
    

]

printformat/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.
from django_extensions.db.models import TimeStampedModel

from django_extensions.db.models import TitleSlugDescriptionModel, \
	TimeStampedModel, TitleDescriptionModel

from project.models import Project


PRINT_ACTION_TYPE_CHOICES  = (
	('Server','Server'),
	('Client','Client')
)
SQL_TYPE_CHOICES = (
	('Nongrid','Nongrid'),
	('Grid','Grid')
)    


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'static/ionicmeta/{0}/mustachehtml/{1}'.format(instance.project.slug,filename)

class PrintFormat(TitleDescriptionModel):
	slug = models.CharField(max_length=100)
	project = models.ForeignKey(Project,on_delete=models.CASCADE)
	action_type = models.CharField(choices=PRINT_ACTION_TYPE_CHOICES,max_length=100)
	htmlfile =  models.FileField(upload_to = user_directory_path)
    
	def __str__(self):
	    return self.title

	class Meta:
		unique_together = ["project", "slug"]

class PrintFormatSQL(models.Model):
	printformat = models.ForeignKey(PrintFormat,on_delete=models.CASCADE)
	sql = models.CharField(max_length=500,blank=True,null=True)
	do = models.PositiveSmallIntegerField(default=0)
	sql_type = models.CharField(choices=SQL_TYPE_CHOICES,max_length=100) 

	class Meta:
		unique_together = ["printformat", "do"]

printformat/forms.py
from django.forms import ModelForm

from django.forms import formset_factory
from django import forms
from .models import PrintFormat,PrintFormatSQL

class PrintFormatForm(ModelForm):
    class Meta:
        model= PrintFormat 
        fields=['title','action_type','htmlfile']
        exclude=['project','slug']     

class PrintFormatSQLForm(ModelForm):
    class Meta:
        model= PrintFormatSQL 
        fields=['sql','do','sql_type']
        exclude=['printformat']    

printformat/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.forms.models import modelformset_factory
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect,HttpResponse,HttpResponseBadRequest

from models import PrintFormat,PrintFormatSQL
from forms import PrintFormatForm,PrintFormatSQLForm
from project.models import Project, Projectwiseusersetup

from slugify import slugify
regex_pattern = r'[^-a-z0-9_]+'


# Create your views here.
        

@csrf_exempt
def printformatindex(request):

    element =Projectwiseusersetup.objects.get(userid=request.session['userid'],project_id = request.session['projectid'])              
    projectselect =Projectwiseusersetup.objects.filter(userid=request.session['userid'])
    if element.setasdefaultproject or request.session['projectid']:
        project_title = element.project_id.title
    
    projectid = request.session['projectid']

    try:
        printFormatObj = PrintFormat.objects.filter(project_id=projectid)
    except PrintFormat.DoesNotExist:
        printFormatObj= None

    return render(request,"printformat.html",locals()) 


PrintFormatSQLFormSet = modelformset_factory(PrintFormatSQL,form = PrintFormatSQLForm,can_delete=True,extra=1) 

def addNewFormat(request):
    
    rpf_form=PrintFormatForm(request.POST or None,request.FILES or None)
    formset = PrintFormatSQLFormSet(request.POST or None,queryset=PrintFormatSQL.objects.none())

    projectid = request.session['projectid']

    if request.method == "POST":
        if rpf_form.is_valid():
            try:
                pfTitle = request.POST.get('title')
                pfaction=rpf_form.save(commit=False)
                pfaction.project_id = projectid
                pfaction.slug = slugify(pfTitle, separator='_', regex_pattern=regex_pattern)
                try:
                    pfaction.save()
                except Exception as e:
                    print e
                    return HttpResponse("TITLE")
                print "**********"
                print pfaction.htmlfile

                for form in formset:
                    if form.is_valid() and form.cleaned_data.get('DELETE') and form.instance.pk:
                        print "************DELETE*******************"
                        print form.instance.pk
                        form.instance.delete()
                    elif form.is_valid() and form.cleaned_data:
                        print "************VALID*********************"
                        print form.is_valid()
                    
                        instance = form.save(commit=False)
                        instance.printformat_id = pfaction.id
                        print instance.id
                        try:
                            instance.save()
                        except Exception as e:
                            print e
                            return HttpResponse("DO")
                    elif not form.is_valid():
                        return HttpResponse("Failure")
                return HttpResponse("Success")
            except Exception as e:
                print e
                return HttpResponse("Failure")

        else:
          return HttpResponse("Failure")
                
    else:
        return render(request,"printformatmodal.html",locals())      

def updtaePFFormat(request,id):
    pfObj = PrintFormat.objects.get(id=id)
    rpf_form=PrintFormatForm(request.POST or None,request.FILES or None,instance=pfObj)
    formset = PrintFormatSQLFormSet(request.POST or None,queryset=PrintFormatSQL.objects.filter(printformat_id=pfObj.id))

    projectid = request.session['projectid']

    if request.method == "POST":
        if rpf_form.is_valid():
            try:
                pfTitle = request.POST.get('title')
                
                pfaction=rpf_form.save(commit=False)
                pfaction.project_id = projectid
                pfaction.slug = slugify(pfTitle, separator='_', regex_pattern=regex_pattern)
                
                try:
                    pfaction.save()
                except Exception as e:
                    print e
                    return HttpResponse("TITLE")
                print "**********"
                print pfaction.htmlfile

                for form in formset:
                    print form.is_valid()
                    if form.is_valid() and form.cleaned_data.get('DELETE') and form.instance.pk:
                        print "************DELETE*******************"
                        print form.instance.pk
                        form.instance.delete()
                    elif form.is_valid() and form.cleaned_data:
                        print "************VALID*********************"
                        print form.is_valid()
                    
                        instance = form.save(commit=False)
                        instance.printformat_id = pfaction.id
                        print instance.id
                        try:
                            instance.save()
                        except Exception as e:
                            print e
                            return HttpResponse("DO")
                    elif not form.is_valid():
                        return HttpResponse("Failure")
                return HttpResponse("Success")
            except Exception as e:
                print e
                return HttpResponse("Failure")

        else:
          return HttpResponse("Failure")
                
    else:
        return render(request,"printformatupdatemodal.html",locals())

def deletePFFormat(request,id):
    query = PrintFormat.objects.get(id=id)
    query.delete()
    return HttpResponseRedirect('/printformat/printformatindex/')
    


printformat/templates/printformat.html
{% extends 'tempmain.html' %} 
{% load static %} 
{% block sidemenu %}
<ul class="sidebar-menu" data-widget="tree">
    <li class="treeview">
        <a href="#">
            <i class="fa fa-dashboard"></i>
            <span>Dashboard</span>
        </a>
    </li>
    <li class="treeview">
        <a href="/rolesetup/roleindex">
            <i class="fa fa-cogs"></i>
            <span>Role Setup</span>
        </a>
    </li >
               
    <li class="treeview">
        <a href="/transaction/enumlist/">
            <i class="fa fa-map-o"></i>
            <span>Enum List</span>
        </a>
    </li>
              
    <li class="treeview">
        <a href="#">
            <i class="fa fa-sign-in"></i> 
            <span>Login</span>
            
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i> 
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="/logintemplate/loginindex/"><i class="fa fa-circle-o"></i> Design login Page</a></li>
            <li><a href="/logintemplate/serverconfig/"><i class="fa fa-circle-o"></i> Server Config</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="/hometemplate/pagecomponent/">
            <i class="fa fa-sticky-note-o"></i> <span>HomePage</span>
        </a>
    </li>
    <li class="treeview">
        <a href="{% url 'transindex' %}">
            <i class="fa fa-file-text"></i> <span>Transaction</span>
        </a>
    </li>
    <li class="treeview">
        <a href="/reportview/repoviewdetails/">
            <i class="fa fa-desktop"></i> <span>ReportView</span>
        </a>
    </li>
    <li class="treeview">
        <a href="/syncmaster/configurations/">
            <i class="fa fa-refresh"></i> <span>Sync Configurations</span>
        </a>
    </li>
    <li class="treeview">
        <a href="/notification/notificationindex/">
           <i class="fa fa-bell-o"></i> <span>Notification Configuration</span>
        </a>
     </li>
     <li class="active">
        <a href="/printformat/printformatindex/">
           <i class="fa fa-print"></i> <span>PrintFormat Configuration</span>
        </a>
     </li>
     <li class="treeview">
        <a href="/eventconfiguration/mapTxnFields/">
            <i class="fa fa-calendar"></i> <span>Event Configuration</span>
        </a>
    </li>
</ul>
{% endblock sidemenu %} 

{% block maincontent %}
<section class="content-header">
   <h1>
      {{project_title}} Print Format Configuration
   </h1>
   <ol class="breadcrumb">
      <li><a href="/transaction/transmain/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"> PrintFormat Configuration</li>
   </ol>
</section>
<!-- /.label above user -->
<div class="col-lg-12 col-xs-4" style="margin:20px 0 0 0;">
   <!-- small box -->
</div>
<!-- /.box-header -->
<div class="box-body">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <div class="col-lg-10 col-xs-2">
                            <h3 class="box-title">Print Format</h3>
                        </div>
                        <button type="button" style="width:80px;" data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#pfAddModal" data-whatever="" class="btn bg-blue selectedit"  onclick="addPFModal(event)">Add New</button>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        {% if printFormatObj %}
                            <table id="example1" class="table table-bordered table-striped" style="border:1px solid lightblue">
                                <thead>
                                    <tr class="bg-light-blue">
                                    <th>PrintFormat Name</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                   
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for printformat in printFormatObj %}
                                    <tr>
                                    <td>{{printformat.title}}</td>
                                    <td>
                                        <button type="button" class="btn bg-olive btn-xs" data-toggle="modal" value="Edit" data-backdrop="static" data-keyboard="false" data-target="#pfEditModal" id="pf_edit" data-pfid="{{printformat.id}}"  onclick="pfEdit(event)"><i class="glyphicon glyphicon-pencil"></i>
                                        </button>
                                    </td>
                                    <td>
                                        <a href="/printformat/deletepf/{{printformat.id}}" data-confirm="Are you sure you want to delete?">
                                            <button type="button" class="btn btn-danger btn-xs"><i class="glyphicon glyphicon-trash"></i></button>
                                        </a>
                                    </td>
                                   
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <p> There are no print format configuration</p>
                        {% endif %}
                    </div>
                     <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
</div>
   <!-- /.content -->

   <div class="modal fade bs-example-modal-lg" id="pfAddModal" role="dialog" aria-labelledby="modalLabel1" aria-hidden="true">
    <div class="modal-dialog modal-lg">
       <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
             <h3 class="modal-title" id="lineModalLabel">New Configuration</h3>
          </div>
          <section>
                  <div id="divErrorPFAdd"></div>
                  <div id="divResultPFAdd"></div>                      
              </section>
          <div class="modal-body" id="pfAddModalBody">
             <!-- content goes here -->
          </div>
       </div>
    </div>
 </div>
   <div class="modal fade bs-example-modal-lg" id="pfEditModal" role="dialog" aria-labelledby="modalLabel1" aria-hidden="true">
      <div class="modal-dialog modal-lg">
         <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
               <h3 class="modal-title" id="lineModalLabel">Edit Configuration</h3>
            </div>
            <section>
                    <div id="divErrorPFEdit"></div>
                    <div id="divResultPFEdit"></div>                      
                </section>
            <div class="modal-body" id="pfEditModalBody">
               <!-- content goes here -->
            </div>
         </div>
      </div>
   </div>
   <!-- /.box-body -->
</div>
<div class="example-modal" >
   <div class="modal" id="processing-modal" role="dialog" aria-hidden="true" data-backdrop="false">
      <div align="center" class="cssload-fond" style="margin:300px 0 0 0;">
         <div id="floatingBarsG">
            <div class="blockG" id="rotateG_01"></div>
            <div class="blockG" id="rotateG_02"></div>
            <div class="blockG" id="rotateG_03"></div>
            <div class="blockG" id="rotateG_04"></div>
            <div class="blockG" id="rotateG_05"></div>
            <div class="blockG" id="rotateG_06"></div>
            <div class="blockG" id="rotateG_07"></div>
            <div class="blockG" id="rotateG_08"></div>
         </div>
         <h3 style="color:white">Please Wait...</h3>
      </div>
   </div>
</div>
<script src="{% static 'maincss/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'maincss/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>

<script>
   $(document).ready(function() {
       $("#processing-modal").modal('show');
       setTimeout(function() {
         $("#processing-modal").modal('hide');  
       },1000);
       $('a[data-confirm]').click(function(ev) {
           var href = $(this).attr('href');
           if (!$('#dataConfirmModal').length) {
               $('body').append('<div id="dataConfirmModal" class="modal fade" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">Please Confirm</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button><a class="btn btn-primary" id="dataConfirmOK">OK</a></div></div></div></div>');
           }
           $('#dataConfirmModal').find('.modal-body').text($(this).attr('data-confirm'));
           $('#dataConfirmOK').attr('href', href);
           $('#dataConfirmModal').modal({
               show: true
           });
           return false;
       });
   });
</script>
   
   
<script>
   $(function() {
       $("#example1").DataTable({
        stateSave: true
       });
   });
</script>

<script>
   $(function () {
     //Initialize Select2 Elements
     $('.select2').select2()
   
   })
</script>
<script src="{% static 'mainjs/printformatjs/printformat.js' %}"></script> 
{% endblock maincontent %}

printformat/templates/printformatmodal.html
{% load static %}
<div class="modal fade" id="pfModalBody" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>
<div role="tabpanel">
	<!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#actionTab" aria-controls="actionTab" role="tab" data-toggle="tab">Add Action</a>

		</li>
		<li role="presentation"><a href="#sqlTab" aria-controls="sqlTab" role="tab" data-toggle="tab">Add SQL</a>

		</li>
	</ul>

	<form id="printformatform" method="POST" enctype="multipart/form-data">
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="actionTab">
				{% csrf_token %}
				<div class="modal-body">

					<div class="form-group">
						<label for="message-text" class="control-label">Title</label>
						<input class="form-control" value="{{ rpf_form.title.value|default_if_none:'' }}" name="title">
					</div>

				
					<div class="form-group">
						<label for="message-text" class="control-label">Action Type</label>
						{{ rpf_form.action_type|default_if_none:'' }}
					</div>
				
					<div class="form-group">
						<label>Add HTML File</label>
						<!-- {{rpf_form.JasperFile}}  -->
						<input type="file" name="htmlfile" required="" id="id_htmlfile" accept=".html"><h4 style="color: indianred">{{ rpf_form.htmlfile.value|default_if_none:'' }}</h4>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="sqlTab">
				{% csrf_token %}
				<div class="modal-body">
					<div id="sqlError">
					</div>
					<table class="table table-striped table-bordered" id="sqlTable">
						<thead class="bg-light-blue">
							<tr>
								<th> SQL </th>
								<th> Type </th>
								<th> Display Order </th>  
								<th> Delete </th>  
							</tr>
						</thead>
						<tbody>  
							{{ formset.management_form }}
							{% for form in formset %}
							{{form.id}} 
								<tr>
									<td>{{form.sql}}</td>
									<td>{{form.sql_type}}</td>
									<td>{{form.do}}</td>
									{% if formset.can_delete %}
										<td> {{form.DELETE}}</td>
									{% else %}
										<td></td>                                    
									{% endif %}   
								</tr>
							{% endfor %}
								
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-danger pull-right" data-dismiss="modal" style="margin-left: 5px;">Cancel</button>
			<button type="button" class="btn btn-success" onclick="printformatsave(event)"> Save </button>
		</div>
	</form>
</div>

<script type="text/javascript">
    $(function() {
        $('#sqlTab tbody > tr').formset({
        prefix: '{{ formset.prefix }}',
        deleteText:'<i class="fa fa-trash" style="color:red;"></i>',
        addText:'<i class="fa fa-plus">Add</i>'
        });
    })
</script>

<script src="{% static 'mainjs/printformatjs/printformat.js' %}"></script>

printformat/templates/printformatupdatemodal.html
{% load static %}
<div class="modal fade" id="pfEditModalBody" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>
<div role="tabpanel">
	<!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#actionTab" aria-controls="actionTab" role="tab" data-toggle="tab">Add Action</a>

		</li>
		<li role="presentation"><a href="#sqlTab" aria-controls="sqlTab" role="tab" data-toggle="tab">Add SQL</a>

		</li>
	</ul>

	<form id="printformateditform" method="POST" enctype="multipart/form-data">
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="actionTab">
				{% csrf_token %}
				<div class="modal-body">

					<div class="form-group">
						<label for="message-text" class="control-label">Title</label>
						<input class="form-control" value="{{ rpf_form.title.value|default_if_none:'' }}" name="title">
					</div>

				
					<div class="form-group">
						<label for="message-text" class="control-label">Action Type</label>
						{{ rpf_form.action_type|default_if_none:'' }}
					</div>
					

					<div class="form-group">
						<label>Add HTML File</label>
						<!-- {{rpf_form.JasperFile}}  -->
						<input type="file" name="htmlfile" required="" id="id_htmlfile" accept=".html"><h4 style="color: indianred">{{ rpf_form.htmlfile.value|default_if_none:'' }}</h4>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="sqlTab">
				{% csrf_token %}
				<div class="modal-body">
					<div id="sqlError">
					</div>
					<table class="table table-striped table-bordered" id="sqlTable">
						<thead class="bg-light-blue">
							<tr>
								<th> SQL </th>
								<th> Type </th>
								<th> Display Order </th>  
								<th> Delete </th>  
							</tr>
						</thead>
						<tbody>  
							{{ formset.management_form }}
							{% for form in formset %}
							{{form.id}} 
								<tr>
									<td>{{form.sql}}</td>
									<td>{{form.sql_type}}</td>
									<td>{{form.do}}</td>
									{% if formset.can_delete %}
										<td> {{form.DELETE}}</td>
									{% else %}
										<td></td>                                    
									{% endif %}   
								</tr>
							{% endfor %}
								
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-danger pull-right" data-dismiss="modal" style="margin-left: 5px;">Cancel</button>
			<button type="button" class="btn btn-success" onclick="printformatupdate(event)" data-pfid={{id}}> Save </button>
		</div>
	</form>
</div>

<script type="text/javascript">
    $(function() {
        $('#sqlTab tbody > tr').formset({
        prefix: '{{ formset.prefix }}',
        deleteText:'<i class="fa fa-trash" style="color:red;"></i>',
        addText:'<i class="fa fa-plus">Add</i>'
        });
    })
</script>

<script src="{% static 'mainjs/printformatjs/printformat.js' %}"></script>