Mobilebuilder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from index import views as index_views
from authentication import views as authen_views
from django.contrib.auth import views as auth_views
from transaction import views as trans_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('index.urls')), 
    url(r'^authentication/', include('authentication.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^usersetup/', include('usersetup.urls')),
    url(r'^project/',include('project.urls')),
    url(r'^transaction/', include('transaction.urls')),
    url(r'^schema/',include('schema.urls')),
    url(r'^transactionview/',include('transactionview.urls')),
    url(r'^logintemplate/',include('logintemplate.urls')),
    url(r'^hometemplate/',include('hometemplate.urls')),
    url(r'^actions/',include('actions.urls')),
    url(r'^reportview/',include('reportview.urls')),
    url(r'^syncmaster/',include('syncmaster.urls')),
    url(r'^generateprocess/',include('generateprocess.urls')),
    url(r'^login/',authen_views.login,name='login'),
    url(r'^$', index_views.base, name='base'),
    url(r'^signout/', index_views.signout, name='signout'),
    url(r'^transindex/',trans_views.transindex, name='transindex'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^favicon.ico$',RedirectView.as_view(url='/static/maincss/images/user.png')),
    url(r'^rolesetup/',include('rolesetup.urls')),
    url(r'^smssetup/',include('smssetup.urls')),
    url(r'^notification/',include('notification.urls')),
    url(r'^printformat/',include('printformat.urls')),
    url(r'^eventconfiguration/',include('eventconfiguration.urls'))
]

home/urls.py
from django.conf.urls import include, url
from . import views


app_name ='home'
urlpatterns = [
	url(r'^main/', views.main, name='main'),
		]

logintemplate/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^loginindex/$', views.loginindex, name='loginindex'),
	url(r'^add/$', views.add, name='add'),
	url(r'^delete/$', views.delete, name='delete'),
	url(r'^serverconfig/$', views.serverconfig, name='serverconfig'),
	url(r'^adduser/$', views.adduser, name='adduser'),
	url(r'^edituser/(?P<userid>.*)$', views.edituser, name='edituser'),
	url(r'^deleteuser/(?P<userid>.*)$', views.deleteuser, name='deleteuser'),
	url(r'^addinfo/$', views.addinfo, name='addinfo'),
	url(r'^editinfo/(?P<infoid>.*)$', views.editinfo, name='editinfo'),
	url(r'^deleteinfo/(?P<infoid>.*)$', views.deleteinfo, name='deleteinfo'),
	url(r'^generateTemplate/(?P<pid>.*)$', views.generateTemplate, name='generateTemplate'),
	url(r'^alreadyLoginpg/(?P<pid>.*)$', views.alreadyLoginpg, name='alreadyLoginpg'),
	url(r'^createLoginpg/(?P<pid>.*)$', views.createLoginpg, name='createLoginpg'),
	url(r'^updateuserindb/$', views.update_user_in_db, name='updateuserindb'),
	url(r'^callService/$', views.callService, name='callService'),
]

logintemplate/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from project.models import Project
from django_extensions.db.models import TimeStampedModel
from rolesetup.models import Role

# Create your models here.
LOGIN_TYPE_CHOICES = (
        ('otp','OTP'),
        ('form','Form'),
        ('bar','Barcode')
)
BGCOLOR_TYPE_CHOICES = (
        ('blue','Blue'),
        ('green','Green'),
        ('red','Red')
)

DB_TYPE_CHOICES = (
        ('new','new'),
		('edited','edited'),
        ('updated','updated'),
		('deleted','deleted')
)

DATA_TYPE_CHOICES = (
        ('integer','Integer'),
		('string','String'),
        ('decimal','Decimal'),
		('date','Date'),
		('datetime','DateTime'),
		('sql','SQL')
)

class Login(TimeStampedModel,models.Model):
	
	title = models.CharField(max_length=100, null=True)
	login_type = models.CharField(max_length=20, choices=LOGIN_TYPE_CHOICES, null=True)
	bgcolor = models.CharField(max_length=250, choices=BGCOLOR_TYPE_CHOICES)
	regeisterion_page = models.BooleanField(default=False)
	logoimg = models.FileField(upload_to = 'static/ionicsrc/images/logo',null=True, blank=True)
	project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
	createpage = models.BooleanField(default=True)

	def __str__(self):
		return self.title

class UserList(TimeStampedModel,models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100,blank=True,null=True)
	mobile_number = models.CharField(max_length=100)
	email_id = models.EmailField(max_length=100)
	password = models.CharField(max_length=100)
	confirm_password = models.CharField(max_length=100)
	is_active = models.BooleanField(default=False)
	role = models.ForeignKey(Role, on_delete=models.CASCADE)
	db_status = models.CharField(max_length=250, choices=DB_TYPE_CHOICES)
	project_id = models.ForeignKey(Project, on_delete=models.CASCADE)

	def __str__(self):
		return self.email_id

	class Meta:
		unique_together = ["project_id", "email_id"]

class GeneralInfo(TimeStampedModel,models.Model):
	key = models.CharField(max_length=100)
	value = models.CharField(max_length=100) 
	db_status = models.CharField(max_length=250, choices=DB_TYPE_CHOICES)
	project_id = models.ForeignKey(Project, on_delete=models.CASCADE)

	def __str__(self):
		return self.key

	class Meta:
		unique_together = ["project_id", "key"]

class EditedUsersList(TimeStampedModel,models.Model):
	user_id = models.CharField(max_length=100)
	user_old_email = models.CharField(max_length=100)
	pid = models.CharField(max_length=100)

	def __str__(self):
		return self.user_old_email

class EditedInfo(TimeStampedModel,models.Model):
	key_id = models.CharField(max_length=100)
	old_key = models.CharField(max_length=100)
	pid = models.CharField(max_length=100)

	def __str__(self):
		return self.old_key






	 

logintemplate/forms.py
from django import forms 
from django.forms import ModelForm
from .models import Login,UserList,GeneralInfo
    
class LoginForm(ModelForm):
    class Meta:
        model = Login
        fields = ['title','login_type','bgcolor','regeisterion_page','logoimg']
        exclude = ['project_id','createpage']


class UserListForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(render_value = True))
    confirm_password = forms.CharField(widget=forms.PasswordInput(render_value = True))
    class Meta:
        model = UserList
        fields = ['first_name','last_name','mobile_number','email_id','password','confirm_password','is_active','role']
        exclude = ['project_id']


class GeneralInfoForm(ModelForm):
    class Meta:
        model = GeneralInfo
        fields = ['key','value']
        exclude = ['project_id','db_status']
        

logintemplate/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect,HttpResponse,HttpResponseBadRequest
#from django.utils.text import slugify
from django.template.defaultfilters import slugify
from slugify import slugify
import re
import json
import os
from django.conf import settings
from django.db.models import Q
import requests
from rolesetup.models import Role


from .models import Login, UserList,GeneralInfo,EditedUsersList,EditedInfo
from .forms import LoginForm,UserListForm,GeneralInfoForm
from .serializers import loginSerializer
from project.models import Project, Projectwiseusersetup
from authentication.models import userprofile
from django.views.decorators.csrf import csrf_exempt
from Mobilebuilder.decorators import myuser_login_required
from .update_user_in_db import update_user_and_generalinfo 
import json
import os
from transaction.models import Transaction
from transactionview.models import Transactionview
from transactionview.serializers import ViewtreeSerializer
from transactionview.views import lists,ionicmetaJson
#from django.db.models import Q
filePath = settings.MEDIA_ROOT

# Create your views here.
@myuser_login_required
def loginindex(request):
	pid = Project.objects.get(pk=request.session['projectid'])
	loginModel = userprofile.objects.get(is_user = True ,id = request.session['userid'])
	element =Projectwiseusersetup.objects.get(userid=loginModel.id,project_id_id = request.session['projectid'] )
	projectselect =Projectwiseusersetup.objects.filter(userid =request.session['userid'])
	project_title = element.project_id.slug
	
	try:
		loginobj = Login.objects.get(project_id_id=pid)
	except Login.DoesNotExist:
		loginobj = None

	if loginobj:
		lform=LoginForm(instance=loginobj)
	else:
		lform = LoginForm() #An Unbound Form



	return render(request, 'loginindex.html', locals())

@csrf_exempt
def add(request):
	
	pid = Project.objects.get(pk=request.session['projectid'])
	try:
		loginobjEdit = Login.objects.get(project_id_id=pid)
	except Login.DoesNotExist:
		loginobjEdit = None
	
	if loginobjEdit:
		if request.method == 'POST':
			form = LoginForm(request.POST,request.FILES,instance=loginobjEdit)
			if form.is_valid():
				editform = form.save(commit=False)
				editform.createpage = False
				editform.save()
				return HttpResponseRedirect('/logintemplate/loginindex/')
			else:
				print form.errors
	else:
		if request.method == 'POST':
			form = LoginForm(request.POST,request.FILES)
			if form.is_valid():
				newform = form.save(commit=False)
				newform.project_id = pid
				newform.createpage = False
				newform.save()
				return HttpResponseRedirect('/logintemplate/loginindex/')
			else:
				print form.errors

	return render(request, 'loginindex.html')

@myuser_login_required
def delete(request):
	
	pid = Project.objects.get(pk=request.session['projectid'])
	
	try:
		
		loginobjDelete = Login.objects.get(project_id_id=pid)
	except Login.DoesNotExist:
		loginobjDelete = None
    
	if loginobjDelete:
		query = Login.objects.get(pk = loginobjDelete.id)
		query.delete()
    
	return HttpResponseRedirect('/logintemplate/loginindex/')  

@myuser_login_required
def serverconfig(request):
	
	loginModel = userprofile.objects.get(is_user = True ,id = request.session['userid'])
	element =Projectwiseusersetup.objects.get(userid=loginModel.id,project_id_id = request.session['projectid'] )
	projectselect =Projectwiseusersetup.objects.filter(userid =request.session['userid'])
	project_title = element.project_id.title
	pid = Project.objects.get(pk=request.session['projectid'])
	
	userObj = UserList.objects.filter(Q(project_id_id=pid) & ~Q(db_status='deleted'))
	infoObj = GeneralInfo.objects.filter(Q(project_id_id=pid) & ~Q(db_status='deleted'))

	infoform = GeneralInfoForm()

	
	return render(request, 'serverconfig.html',locals())

@csrf_exempt
def adduser(request):
	pid = Project.objects.get(pk=request.session['projectid'])
	
	if request.method == 'POST':
		userform = UserListForm(request.POST)
		# password = request.POST.get('password')
		# url = 'http://192.168.125.75:32923/mservice/mobileserviceapi/encryptStr'
		# data = {"data" : password}
		# response = requests.post(url, params=data)
		
		try:
			if userform.is_valid():
				newUser = userform.save(commit=False)
				# newUser.password = response.text
				# newUser.confirm_password = response.text
				newUser.project_id = pid
				newUser.is_active = True
				newUser.db_status = 'new'
				newUser.save()
				return HttpResponse("Success")
			else:
				print userform.errors
				return HttpResponse("Failure2")
		except Exception as e:
			print e
			return HttpResponse("Failure1")

		
	else:
		# roleObj = Role.objects.filter(projectid_id=pid)
		userform = UserListForm()
		userform.fields["role"].queryset = Role.objects.filter(projectid_id=pid)

		return render(request,'usermodal.html',locals())

def edituser(request,userid):
	pid = Project.objects.get(pk=request.session['projectid'])
	userObj = UserList.objects.get(id=userid)
	old_status = userObj.db_status
	print old_status
	
	if request.method == 'POST':
		# password = request.POST.get('password')
		# url = 'http://192.168.125.75:32923/mservice/mobileserviceapi/encryptStr'
		# data = {"data" : password}
		# response = requests.post(url, params=data)
		
		if old_status != 'new':
			try:
				existingData = EditedUsersList.objects.get(user_id=userObj.id)
			except EditedUsersList.DoesNotExist:
				existingData = None
			
			if existingData == None:
				user_backup_tab = EditedUsersList()
				user_backup_tab.user_id = userObj.id
				user_backup_tab.user_old_email = userObj.email_id
				user_backup_tab.pid = userObj.project_id_id
				user_backup_tab.save()
			else:
				existingData.user_old_email = userObj.email_id
				existingData.save()
			
		userform = UserListForm(request.POST,instance=userObj)
		
		try:
			if userform.is_valid():
				if old_status == 'new':
					edditedUser = userform.save(commit=False)
					# edditedUser.password = response.text
					# edditedUser.confirm_password = response.text
					edditedUser.save()
					
				else:
					uform = userform.save(commit=False)
					# uform.password = response.text
					# uform.confirm_password = response.text
					uform.db_status = 'edited'
					uform.save()

				
				return HttpResponse("Success")
			else:
				print form.errors
				return HttpResponse("Failure2")
		except Exception as e:
			print e
			return HttpResponse("Failure1")

		
	else:
		userform = UserListForm(instance=userObj)
		userform.fields["role"].queryset = Role.objects.filter(projectid_id=pid)
		return render(request,'usereditmodal.html',locals())
	
    
	

@myuser_login_required
def deleteuser(request,userid):
	
	try:
		query = UserList.objects.get(id=userid)
	except Login.DoesNotExist:
		query = None
    
	if query:
		query.db_status = 'deleted'
		query.save()    
	return HttpResponseRedirect('/logintemplate/serverconfig/') 

def addinfo(request):
	
	pid = Project.objects.get(pk=request.session['projectid'])
	
	if request.method == 'POST':
		infoform = GeneralInfoForm(request.POST)
		try:
			if infoform.is_valid():
				newInfo = infoform.save(commit=False)
				newInfo.project_id = pid
				newInfo.db_status = 'new'
				newInfo.save()
				return HttpResponse("Success")
			else:
				print infoform.errors
				return HttpResponse("Failure2")
		except Exception as e:
			print e
			return HttpResponse("Failure1")

def editinfo(request,infoid):

	pid = Project.objects.get(pk=request.session['projectid'])
	editInfoObj = GeneralInfo.objects.get(id=infoid)
	old_status = editInfoObj.db_status
	print old_status
	
	if request.method == 'POST':

		if old_status != 'new':
			try:
				existingData = EditedInfo.objects.get(key_id=editInfoObj.id)
			except EditedInfo.DoesNotExist:
				existingData = None
			
			if existingData == None:
				info_backup_tab = EditedInfo()
				info_backup_tab.key_id = editInfoObj.id
				info_backup_tab.old_key = editInfoObj.key
				info_backup_tab.pid = editInfoObj.project_id_id
				info_backup_tab.save()
			else:
				existingData.old_key = editInfoObj.key
				existingData.save()

		infoform = GeneralInfoForm(request.POST,instance=editInfoObj)
		try:
			if infoform.is_valid():

				if old_status == 'new':
					infoform.save()
				else:
					iform = infoform.save(commit=False)
					iform.db_status = 'edited'
					iform.save()
				
				return HttpResponse("Success")
			else:
				print infoform.errors
				return HttpResponse("Failure2")
		except Exception as e:
			print e
			return HttpResponse("Failure1")
	else:
		infoform = GeneralInfoForm(instance=editInfoObj)
		return render(request,'infoeditmodal.html',locals())


def deleteinfo(request,infoid):

	try:
		query = GeneralInfo.objects.get(id=infoid)
	except Login.DoesNotExist:
		query = None
    
	if query:
		query.db_status = 'deleted'
		query.save()
    
	return HttpResponseRedirect('/logintemplate/serverconfig/')


def generateTemplate(pid):
	filePath = settings.MEDIA_ROOT
	lstarthtml = ""
	lbodyhtml =""
	lcontenthtml =""
	lbodystart = ""
	lbodyend=""
	lbodyhtml=""
	lendhtml =""
	lheaderhtml ="""<ion-header></ion-header><ion-content class="background">"""
	lendhtml ="""</ion-content>"""
	lbodystart = """<div><div style="background-image: url('images/bg-01.jpg');"><div class="wrap-login100"><form class="login100-form validate-form"><span class="login100-form-logo"><img src="assets/imgs/logo.png" style="width:50%" /></span><span class="login100-form-title p-b-34 p-t-27">Log in</span>"""
	login  = Login.objects.get(project_id_id = pid)

logintemplate/templates/infoeditmodal.html
{% load static %}

<div class="modal fade" id="infoEditModelbody" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>
    <form id="infoEditForm" method="POST">
        {% csrf_token %}
        <div class="modal-body">
            <div class="form-group">
                <label for="key" class="control-label">Key:</label>
                {{infoform.key}}
            </div>
            <div class="form-group">
                <label for="value" class="control-label">Value:</label>
                {{infoform.value}}
            </div>            
            
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="sumbit" class="btn btn-success" id="updateinfo" data-infoid="{{infoid}}">Save</button>
            </div>
        </div>
    </form>    

  


logintemplate/templates/loginindex.html
{% extends 'tempmain.html' %}
{% load static %}
    {% block sidemenu  %}
      
      <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu tree" data-widget="tree">
        <li class="treeview">
            <a href="#">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            </a>
        </li>
        <li class="treeview">
            <a href="/rolesetup/roleindex">
                <i class="fa fa-cogs"></i> <span>Role Setup</span>
            </a>
        </li >

         <li class="treeview">
            <a href="/transaction/enumlist/">
                <i class="fa fa-map-o"></i> <span>Enum List</span>
            </a>
        </li>

        <li class="treeview active menu-open">
            <a href="#">
                <i class="fa fa-sign-in"></i> 
                <span>Login</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i> 
                </span>
            </a>
    
            <ul class="treeview-menu">
                <li class="active"><a href="/logintemplate/loginindex/"><i class="fa fa-circle-o"></i> Design login Page</a></li>
                <li><a href="/logintemplate/serverconfig/"><i class="fa fa-circle-o"></i> Server Config</a></li>
            </ul>
        </li>
        
        {% if loginobj.createpage %}
            <li class="bg-green-active" id="createLoginlb">
            <a id="createLoginpg" data-pid ="{{pid.id}}" data-from="view">
                <i class="fa fa-product-hunt"></i> <span>Generate Login Page</span>
                <span class="pull-right-container">
                    <!--    <i class="fa fa-angle-left pull-right"></i> -->
                </span>
            </a>
            </li>
            {% else %}
            <li class="bg-blue" id="createLoginlb">
            <a id="createLoginpg" data-pid ="{{pid.id}}" data-from="view">
                <i class="fa fa-product-hunt"></i> <span>Generate Login Page</span>
                <span class="pull-right-container">
                    <!--    <i class="fa fa-angle-left pull-right"></i> -->
                </span>
            </a>
            </li>
        {% endif %}
       
       <li class="treeview">
            <a href="/hometemplate/pagecomponent/">
                <i class="fa fa-sticky-note-o"></i> <span>HomePage</span>
            </a>
        </li>
       
        <li class="treeview">
            <a href="{% url 'transindex' %}">
                <i class="fa fa-file-text"></i>
                <span>Transaction</span>
           </a>
        </li>
        
        
        <li class="treeview">
            <a href="/reportview/repoviewdetails/">
                <i class="fa fa-desktop"></i> <span>ReportView</span>
            </a>
        </li>

        <li class="treeview">
            <a href="/syncmaster/configurations/">
                <i class="fa fa-refresh"></i> <span>Sync Configurations</span>
            </a>
        </li>


        <li class="treeview">
            <a href="/notification/notificationindex/">
                <i class="fa fa-bell-o"></i> <span>Notification Configuration</span>
            </a>
        </li>   
        <li class="treeview">
            <a href="/printformat/printformatindex/">
               <i class="fa fa-print"></i> <span>PrintFormat Configuration</span>
            </a>
        </li>
        <li class="treeview">
            <a href="/eventconfiguration/mapTxnFields/">
                <i class="fa fa-calendar"></i> <span>Event Configuration</span>
            </a>
        </li>
    </ul>

    {% endblock sidemenu %}
{% block maincontent %}
<!-- Content Header (Page header) -->
<div id="divErrorMessages"></div>
<div id="divResults"></div>
<section class="content-header">
   <h1> Create </h1>
   <ol class="breadcrumb">
      <li> <a href="/transaction/transmain/"> <i class="fa fa-dashboard"> </i> Home </a> </li>
      <li class="active">Design Login Page</li>
   </ol>
</section>
<section class="content">
   <div class="row">
      <!-- left column -->
      <div class="col-md-12">
         <!-- general form elements -->
         <div class="box box-primary">
            <div class="box-header with-border">
               <h3 class="box-title">Login Type</h3>
            </div>
            <!-- /.box-header -->
            <form id="form" method="POST" action ="{% url 'add' %}" enctype="multipart/form-data">
               {% csrf_token %}
               <div class="box-body">
                  <div class="form-group">
                     <label for="title">Title</label>
                     <!-- <input type="text" class="form-control" name="title" value="{{ lform.title.value|default_if_none:'' }}" required="" id="id_title" maxlength="250"> -->
                     {{lform.title}}
                  </div>
                  <div class="form-group">
                     <label for="logintype">Login Type</label>
                     {{lform.login_type}}
                  </div>
                  <div class="form-group">  
                     <label for="bgc">Background Color</label>
                     {{lform.bgcolor}}
                  </div>
                  <div class="form-group">
                <label>Logo Image</label>

                <div class="form-group">
                  <label for="exampleInputFile">File input</label>
                  <input type="file" name="logoimg" id="logoimg" value="{{ form.logoimg.value|default_if_none:'' }}">

                  <p class="help-block">Please Upload image Only in png format.</p>
                </div>
                  <div class="form-group">
                     <label for="regpage">Need a Registeration Page?</label> 
                     <label class="switch">
                        {{lform.regeisterion_page}}
                        <div class="slider round"></div>
                     </label>
                  </div>
               </div>
               <!-- /.box-body -->
               <!-- </form> -->
               <div class="box-footer">
                  <button type="submit" class="btn btn-success">Save</button>   
                  <a href="/logintemplate/delete/" data-confirm="Are you sure you want to delete?"> <button type="button" class="btn btn-danger" data-dismiss="modal">Delete</button></a>
               </div>
         </div>
         </form>
      </div>
   </div>
</section>
<div class="example-modal">
   <div class="modal" id="processing-modal" role="dialog" aria-hidden="true" data-backdrop="false">
      <div align="center" class="cssload-fond" style="margin:300px 0 0 0;">
         <div id="floatingBarsG">
            <div class="blockG" id="rotateG_01"></div>
            <div class="blockG" id="rotateG_02"></div>
            <div class="blockG" id="rotateG_03"></div>
            <div class="blockG" id="rotateG_04"></div>
            <div class="blockG" id="rotateG_05"></div>
            <div class="blockG" id="rotateG_06"></div>
            <div class="blockG" id="rotateG_07"></div>
            <div class="blockG" id="rotateG_08"></div>
         </div>
         <h3 style="color:white">Please Wait...</h3>
      </div>
   </div>
</div>
{% block script  %}
<!-- Jquery -->
<script src="{% static 'maincss/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'maincss/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'mainjs/logintemplatejs/logintemplate.js' %}"></script>
{% endblock script  %}
<script type="text/javascript">
   $(document).ready(function() {
       $("#processing-modal").modal('show');
       setTimeout(function() {
           $("#processing-modal").modal('hide');
       }, 300);
       $('a[data-confirm]').click(function(ev) {
           var href = $(this).attr('href');
           if (!$('#dataConfirmModal').length) {
               $('body').append('<div id="dataConfirmModal" class="modal fade" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">Please Confirm</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button><a class="btn btn-primary" id="dataConfirmOK">OK</a></div></div></div></div>');
           }
           $('#dataConfirmModal').find('.modal-body').text($(this).attr('data-confirm'));
           $('#dataConfirmOK').attr('href', href);
           $('#dataConfirmModal').modal({
               show: true
           });
           return false;
       });
       $("#conntable").DataTable({
        stateSave: true
       });
   });
</script>
{% endblock %}

logintemplate/templates/usereditmodal.html
{% load static %}

<div class="modal fade" id="userEditModelbody" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>

<form id="usereditform" method="POST">
{% csrf_token %}
    
    <div class="form-group">
        <label for="logintype">First Name</label>
        <!-- <input type="text" class="form-control" name="title" value="{{ form.title.value|default_if_none:'' }}" id="id_title"> -->
        {{userform.first_name}}
    </div>
    
    <div class="form-group" >  
        <label for="bg">Last name</label>
        <!-- <input type="text" class="form-control" name="description" value="{{ form.description.value|default_if_none:'' }}"> -->
        {{userform.last_name}}
    </div>
    
    <div class="form-group" >
        <label for="layput">Mobile Number</label>
       {{userform.mobile_number}}
    </div>
    
    <div class="form-group" >
        <label for="layput">Email Id</label>
       {{userform.email_id}}
    </div>
    
    <div class="form-group" >
        <label for="layput">Password</label>
       {{userform.password}}
    </div>
    
    <div class="form-group" >
        <label for="layput">Confirm Password</label>
       {{userform.confirm_password}}
    </div>

    <div class="form-group" >
        <label for="layput">Role</label>
       {{userform.role}}
    </div>

    <div class="form-group">
        <label for="regpage">Is User Active?</label> 
        <label class="switch">
            {{userform.is_active}}
            <div class="slider round"></div>
        </label>
    </div>

    

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="sumbit" class="btn btn-success" id="updateUser" data-userid="{{userid}}">Save</button>
    </div>
</form>           

  
